import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Navbar/Navbar";
import Filter from "@/components/Filter/Filter";
import EventList from "@/components/EventList/EventList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Acme&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={styles.main}>
        <Header />
        <Navbar />
        <Filter />
        <EventList />
      </main>
    </>
  );
}
